# Generated by Django 2.2.8 on 2019-12-24 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('email_address', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('admin_notified', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
