# Generated by Django 2.2.8 on 2019-12-17 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('tutorials', '0002_auto_20191217_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='tutorials_tutorialplugin', serialize=False, to='cms.CMSPlugin')),
                ('tutorial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tutorials.Tutorial')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
