# Generated by Django 2.2.8 on 2019-12-17 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('tutorials', '0003_tutorialplugin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TutorialPlugin',
        ),
    ]
