# Generated by Django 2.2.8 on 2019-12-17 06:20

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutorials', '0005_delete_tutorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('body', djangocms_text_ckeditor.fields.HTMLField()),
                ('tutorial_title', models.CharField(max_length=200)),
            ],
        ),
    ]
