# Generated by Django 2.2.8 on 2019-12-17 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_tutorial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
