# Generated by Django 2.2.8 on 2019-12-17 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('custom_cms_plugins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='custom_cms_plugins_cardplugin', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(max_length=10)),
                ('body', models.TextField()),
                ('main_internal_text', models.CharField(blank=True, max_length=10)),
                ('main_internal_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page', verbose_name='Main internal link')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
