# Generated by Django 2.2.8 on 2019-12-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_cms_plugins', '0003_auto_20191217_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardplugin',
            name='title_tag',
            field=models.CharField(blank=True, choices=[('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3'), ('h4', 'h4'), ('h5', 'h5'), ('h6', 'h6'), ('span', 'span')], default='span', max_length=10),
        ),
    ]
