# Generated by Django 2.2.8 on 2019-12-21 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('custom_cms_plugins', '0004_auto_20191217_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleSubscribePlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='custom_cms_plugins_simplesubscribeplugin', serialize=False, to='cms.CMSPlugin')),
                ('submit_url_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('is_recaptcha_enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
