# Generated by Django 2.2.8 on 2019-12-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_cms_plugins', '0005_simplesubscribeplugin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplesubscribeplugin',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='simplesubscribeplugin',
            name='name',
        ),
        migrations.AddField(
            model_name='simplesubscribeplugin',
            name='has_name',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
